- name: Setup VOF base image
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  
  roles:
    - create-vof-user
    - install-dependencies
    - install-postgresql
    - install-ruby
    - install-elk-beats
    - install-logging-agent
    - starting-supervisor
    - cleanup-home-dir
