metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
    - core
    - diskio
    - fsstat
    - load
    - process_summary
    - raid
    - socket
    - uptime
  enabled: true
  period: 60s
  processes: ['.*']
  cpu_ticks: false

output:
  logstash:
    hosts: ["192.168.1.2:5044"]
    bulk_max_size: 1024

    ssl:
      certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]

shipper:

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB

setup.kibana:
  host: "192.168.1.2:5601"