filebeat:
  prospectors:
    -
      paths:
        - /home/vof/app/log/logstash_*.log

      exclude_lines: ['/health{1}']
      #  - /var/log/*.log

      input_type: log

      document_type: syslog

  registry_file: /var/lib/filebeat/registry

output:
  logstash:
    hosts: ['192.168.1.2:5044']
    bulk_max_size: 1024

    ssl:
      certificate_authorities: ['/etc/pki/tls/certs/logstash-forwarder.crt']

shipper:

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB